[package]

name = "session"
version = "0.1.0"
authors = ["Zach Pomerantz <zmp@umich.edu>"]

[[lib]]

name = "session"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

